### ISSUE TITLE
parallel download episodes

### ISSUE THREAD

**Issue by sebyx07** [DavsX/SipsDownloader#1]
i think having a pool of workers downloading will make it really fast. i will look work on it this weekend and make a pr

**Comment by DavsX** [comment]
Agreed. I have plans for this as well, but I didn't yet get to OTP/processes yet in erlang :) Keen in mind, that the site itself limits the number of simultaneous downloads to ~8 (5 is five for sure, but 10 is too much) - that was my experience, when at first I started to download them manually :)

**Comment by DavsX** [comment]
Version 0.2.0 does parallel downloads.
